use_frameworks!

platform :ios, '10.0'

target 'PrettyPopover_Example' do
  pod 'PrettyPopover', :path => '../'

  target 'PrettyPopover_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
