source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '11.0'

target 'PrettyPopover_Example' do
  pod 'PrettyPopover', :path => '../'
  
  pod 'LoveUIKit', '0.0.5'
  pod 'LookinServer', '1.0.6', :configurations => ['Debug']

  target 'PrettyPopover_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Guanghui Liang"
end
