name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install Dependences
      run: |
        cd Example
        pod repo update
        pod install
      shell: bash
    - name: Test and Lint
      uses: ty0x2333/cocoapods-action@master
      with:
        additional_build_params: -destination 'platform=iOS Simulator,id=ED60A719-6E1A-47AA-BB47-53683C1584D6'
    - name: Upload coverage to Codecov
#       run: |
#         curl -Os https://uploader.codecov.io/latest/macos/codecov
#         chmod +x codecov
#         ./codecov
      uses: codecov/codecov-action@v3.1.1
#       with:
#         directory: ./coverage/reports/
#         fail_ci_if_error: true
#         files: ./coverage1.xml,./coverage2.xml
#         name: codecov-umbrella
#         path_to_write_report: ./coverage/codecov_report.txt
#         verbose: true
