name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install Dependences
      run: |
        cd Example
        pod repo update
        pod install
      shell: bash
    - name: Test and Lint
      uses: ty0x2333/cocoapods-action@master
      with:
        additional_build_params: -destination 'platform=iOS Simulator,id=ED60A719-6E1A-47AA-BB47-53683C1584D6' -configuration Debug CODE_SIGNING_ALLOWED=NO | xcpretty -c
          mv ~/Library/Developer/Xcode/DerivedData/ ./DerivedData/iOS
    - name: Code Coverage
      run: |
        set -o pipefail
        export PATH="/usr/local/opt/curl/bin:$PATH"
        curl --version
        bash <(curl -s https://codecov.io/bash) -D './DerivedData/iOS' -J '^SDWebImage$' -c -X gcov -F ios
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.1
